name: mydemo1
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_speed_dial: 7.0.0

  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  easy_localization: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0




flutter:

  uses-material-design: true

  assets:
      - assets/images/
      - assets/fonts/
      - assets/translations/

  fonts:
     - family: Billabong
       fonts:
         - asset: assets/fonts/Billabong.ttf

